# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'savvy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  # Pods for savvy

  target 'savvyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'savvy-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for savvy-tvOS

  target 'savvy-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
